### ISSUE TITLE
[BUG] can't access camera on miui 11/12

### ISSUE THREAD

**Issue by PointVoider** [ElderDrivers/EdXposed#707]
**什么情况/What happened?**
camera app doesn't work and if an app trying to access camera, the app freeze
如无法开机/模块无效等

**Xposed模块列表/Xposed Module List**
nothing

允许截图/Screenshot allowed

**Magisk模块列表/Magisk Module List**
just riru

允许截图/Screenshot allowed

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed:
0.4.6.4
Riru:
21.3

matlog filtered with 'camera':
[2020-12-04-15-18-50.txt](https://github.com/ElderDrivers/EdXposed/files/5641110/2020-12-04-15-18-50.txt)

**相关Logcat/Logcat**

有助于定位问题，必须使用我们的log抓取模块抓取/It can help us to locate issue, must use our logcat module

**Comment by kotori2** [comment]
Fixed yesterday

**Comment by PointVoider** [comment]
> Fixed yesterday

then am i using old version or what?
i just installed it a few minutes ago and i still can't access my camera

**Comment by kotori2** [comment]
@PointVoider use canary with riru v22+

**Comment by PointVoider** [comment]
> @PointVoider use canary with riru v22+

im sorry for asking this.
canary what? magisk? edxposed?

**Comment by kotori2** [comment]
@PointVoider Both of them if possible.

**Comment by PointVoider** [comment]
ok, thanks
